version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: db-oracle
    restart: unless-stopped
    ports:
      - '1521:1521'
    environment:
      ORACLE_PASSWORD: db_secret_2024
      APP_USER: db_admin
      APP_USER_PASSWORD: db_secret_2024
    volumes:
      - db_oracledata:/opt/oracle/oradata

volumes:
  db_oracledata:
