/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#fe9261",
              "surface-variant": "#d8e3fb",
              "tertiary-fixed-dim": "#ffb596",
              "on-secondary": "#ffffff",
              "on-primary-fixed": "#001848",
              "tertiary-container": "#752a00",
              "on-surface-variant": "#434652",
              "on-secondary-container": "#6c4d00",
              "inverse-primary": "#b2c5ff",
              "surface-tint": "#365aaf",
              "surface-border": "#E2E8F0",
              "on-secondary-fixed": "#271900",
              "secondary-fixed": "#ffdea6",
              "status-submitted": "#3B82F6",
              "outline-variant": "#c4c6d3",
              "on-surface": "#111c2d",
              "surface-container-lowest": "#ffffff",
              "background": "#f9f9ff",
              "on-secondary-fixed-variant": "#5e4200",
              "tertiary": "#511b00",
              "on-primary-container": "#8eadff",
              "on-tertiary-fixed-variant": "#7b2f04",
              "outline": "#747783",
              "on-error-container": "#93000a",
              "status-draft": "#94A3B8",
              "surface-container-highest": "#d8e3fb",
              "primary-container": "#0f3d91",
              "primary-fixed": "#dae2ff",
              "surface-container": "#e7eeff",
              "status-good": "#22C55E",
              "on-tertiary-fixed": "#360f00",
              "on-background": "#111c2d",
              "on-primary": "#ffffff",
              "surface-container-high": "#dee8ff",
              "secondary": "#7c5800",
              "primary": "#00286a",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#ffdbcd",
              "surface": "#f9f9ff",
              "inverse-surface": "#263143",
              "secondary-fixed-dim": "#ffbb16",
              "status-bad": "#EF4444",
              "status-poor": "#F97316",
              "secondary-container": "#ffbb16",
              "surface-dim": "#cfdaf2",
              "surface-container-low": "#f0f3ff",
              "error-container": "#ffdad6",
              "primary-fixed-dim": "#b2c5ff",
              "on-error": "#ffffff",
              "inverse-on-surface": "#ecf1ff",
              "status-fair": "#EAB308",
              "on-primary-fixed-variant": "#174296",
              "surface-background": "#F8FAFC",
              "surface-bright": "#f9f9ff",
              "error": "#ba1a1a"
      },
      "spacing": {
              "xl": "32px",
              "sm": "8px",
              "xs": "4px",
              "md": "16px",
              "grid-margin": "24px",
              "base": "4px",
              "lg": "24px",
              "grid-gutter": "16px",
              "container-max-width": "1440px"
      },
      "fontFamily": {
              "body-md": ["Hanken Grotesk", "sans-serif"],
              "label-md": ["JetBrains Mono", "monospace"],
              "body-lg": ["Hanken Grotesk", "sans-serif"],
              "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
              "headline-sm": ["Hanken Grotesk", "sans-serif"],
              "headline-md": ["Hanken Grotesk", "sans-serif"],
              "table-data": ["Hanken Grotesk", "sans-serif"],
              "display-lg": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "table-data": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
              "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}

