import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783410160945 implements MigrationInterface {
    name = 'InitialSchema1783410160945'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "CRITERIA" ("id" number GENERATED BY DEFAULT AS IDENTITY, "parameterId" number NOT NULL, "good" float NOT NULL, "fair" float NOT NULL, "poor" float NOT NULL, "judgementBasis" clob NOT NULL, "effectiveFrom" timestamp NOT NULL, "effectiveTo" timestamp, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_3a09e027845e58ba5464cd75bb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "TEST_RESULT" ("id" number GENERATED BY DEFAULT AS IDENTITY, "testSessionId" number NOT NULL, "parameterId" number NOT NULL, "value" float, "score" float, "judgement" varchar2(20) NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_f19d47143a3d9bac5b6fb843150" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "PARAMETER" ("id" number GENERATED BY DEFAULT AS IDENTITY, "testTypeId" number NOT NULL, "name" varchar2(100) NOT NULL, "unit" varchar2(50), "comparisonDirection" varchar2(10) NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_5983bc08b1d2b60b080919a1419" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "EQUIPMENT_TEST_TYPE" ("id" number GENERATED BY DEFAULT AS IDENTITY, "equipmentType" varchar2(100) NOT NULL, "testTypeId" number NOT NULL, "isMandatory" number(1) DEFAULT 0 NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_ac9df496b4bfd22b602626587a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "DAMAGE_MECHANISM" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "description" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_7bc53eeb8a031db971b1810e9bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "DM_TEST_TYPE" ("id" number GENERATED BY DEFAULT AS IDENTITY, "damageMechanismId" number NOT NULL, "testTypeId" number NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_b59836aff4755b5f62afbd4b1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "TEST_TYPE" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "description" varchar2(255), "isActive" number(1) DEFAULT 1 NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_602bafb0fa88d64cdba9817ce49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "TEST_SESSION" ("id" number GENERATED BY DEFAULT AS IDENTITY, "assetId" number NOT NULL, "testTypeId" number NOT NULL, "testYear" number NOT NULL, "status" varchar2(50) DEFAULT 'DRAFT' NOT NULL, "createdById" number, "approvedById" number, "approvedAt" timestamp, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_28a2b83561066b254e422325bd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "AUDIT_LOG" ("id" number GENERATED BY DEFAULT AS IDENTITY, "userId" number NOT NULL, "action" varchar2(100) NOT NULL, "tableName" varchar2(100) NOT NULL, "recordId" number NOT NULL, "oldData" clob, "newData" clob, "reason" varchar2(1000), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_3242e5535570d2285972c746d3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "USERS" ("id" number GENERATED BY DEFAULT AS IDENTITY, "email" varchar2(255) NOT NULL, "passwordHash" varchar2(255), "name" varchar2(100) NOT NULL, "role" varchar2(50) DEFAULT 'VIEWER' NOT NULL, "isActive" number(1) DEFAULT 1 NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "UQ_a1689164dbbcca860ce6d17b2e1" UNIQUE ("email"), CONSTRAINT "PK_b16c39a00c89083529c6166fa5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "USER_UBP_ACCESS" ("id" number GENERATED BY DEFAULT AS IDENTITY, "userId" number NOT NULL, "ubpId" number NOT NULL, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_13f804d2dd96e74d7ac306fe80f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "UBP" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "description" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "UQ_453ac3346b800942bd063087e49" UNIQUE ("name"), CONSTRAINT "PK_d758a0e5fe21a237714efd23152" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ASSET" ("id" number GENERATED BY DEFAULT AS IDENTITY, "ubpId" number NOT NULL, "name" varchar2(100) NOT NULL, "equipmentType" varchar2(100) NOT NULL, "notes" clob, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_25f23885176fe65345a4fb09b5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "CRITERIA" ADD CONSTRAINT "FK_824bf8db29ad093e7eeae585988" FOREIGN KEY ("parameterId") REFERENCES "PARAMETER" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_RESULT" ADD CONSTRAINT "FK_568c8db36565a640c57a9ca9821" FOREIGN KEY ("testSessionId") REFERENCES "TEST_SESSION" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_RESULT" ADD CONSTRAINT "FK_c9c6fa3ac60c6dfe65d0922abd5" FOREIGN KEY ("parameterId") REFERENCES "PARAMETER" ("id")`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" ADD CONSTRAINT "FK_1fc90faa3e50989673fe657ed90" FOREIGN KEY ("testTypeId") REFERENCES "TEST_TYPE" ("id")`);
        await queryRunner.query(`ALTER TABLE "EQUIPMENT_TEST_TYPE" ADD CONSTRAINT "FK_5b5e0ee96f70b214bd41932a6f3" FOREIGN KEY ("testTypeId") REFERENCES "TEST_TYPE" ("id")`);
        await queryRunner.query(`ALTER TABLE "DM_TEST_TYPE" ADD CONSTRAINT "FK_e39992105a0752b19101e58dea7" FOREIGN KEY ("damageMechanismId") REFERENCES "DAMAGE_MECHANISM" ("id")`);
        await queryRunner.query(`ALTER TABLE "DM_TEST_TYPE" ADD CONSTRAINT "FK_7afba923cc904f0ffb97ed40d89" FOREIGN KEY ("testTypeId") REFERENCES "TEST_TYPE" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" ADD CONSTRAINT "FK_f6030e7f63d2599e6c8c1cf4130" FOREIGN KEY ("assetId") REFERENCES "ASSET" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" ADD CONSTRAINT "FK_914877752936d4048117379c69b" FOREIGN KEY ("testTypeId") REFERENCES "TEST_TYPE" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" ADD CONSTRAINT "FK_88c3575497a6dd8843f055abe67" FOREIGN KEY ("createdById") REFERENCES "USERS" ("id")`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" ADD CONSTRAINT "FK_5dc07274cc866bfbc6a1791a709" FOREIGN KEY ("approvedById") REFERENCES "USERS" ("id")`);
        await queryRunner.query(`ALTER TABLE "AUDIT_LOG" ADD CONSTRAINT "FK_c9040e7ce7ba702fe1a0b385cf2" FOREIGN KEY ("userId") REFERENCES "USERS" ("id")`);
        await queryRunner.query(`ALTER TABLE "USER_UBP_ACCESS" ADD CONSTRAINT "FK_00fe0b133346ca525391d6e7e51" FOREIGN KEY ("userId") REFERENCES "USERS" ("id")`);
        await queryRunner.query(`ALTER TABLE "USER_UBP_ACCESS" ADD CONSTRAINT "FK_556e3572ba926e8eebce87006c3" FOREIGN KEY ("ubpId") REFERENCES "UBP" ("id")`);
        await queryRunner.query(`ALTER TABLE "ASSET" ADD CONSTRAINT "FK_8f9179f53364b7f049df4d0d695" FOREIGN KEY ("ubpId") REFERENCES "UBP" ("id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ASSET" DROP CONSTRAINT "FK_8f9179f53364b7f049df4d0d695"`);
        await queryRunner.query(`ALTER TABLE "USER_UBP_ACCESS" DROP CONSTRAINT "FK_556e3572ba926e8eebce87006c3"`);
        await queryRunner.query(`ALTER TABLE "USER_UBP_ACCESS" DROP CONSTRAINT "FK_00fe0b133346ca525391d6e7e51"`);
        await queryRunner.query(`ALTER TABLE "AUDIT_LOG" DROP CONSTRAINT "FK_c9040e7ce7ba702fe1a0b385cf2"`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" DROP CONSTRAINT "FK_5dc07274cc866bfbc6a1791a709"`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" DROP CONSTRAINT "FK_88c3575497a6dd8843f055abe67"`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" DROP CONSTRAINT "FK_914877752936d4048117379c69b"`);
        await queryRunner.query(`ALTER TABLE "TEST_SESSION" DROP CONSTRAINT "FK_f6030e7f63d2599e6c8c1cf4130"`);
        await queryRunner.query(`ALTER TABLE "DM_TEST_TYPE" DROP CONSTRAINT "FK_7afba923cc904f0ffb97ed40d89"`);
        await queryRunner.query(`ALTER TABLE "DM_TEST_TYPE" DROP CONSTRAINT "FK_e39992105a0752b19101e58dea7"`);
        await queryRunner.query(`ALTER TABLE "EQUIPMENT_TEST_TYPE" DROP CONSTRAINT "FK_5b5e0ee96f70b214bd41932a6f3"`);
        await queryRunner.query(`ALTER TABLE "PARAMETER" DROP CONSTRAINT "FK_1fc90faa3e50989673fe657ed90"`);
        await queryRunner.query(`ALTER TABLE "TEST_RESULT" DROP CONSTRAINT "FK_c9c6fa3ac60c6dfe65d0922abd5"`);
        await queryRunner.query(`ALTER TABLE "TEST_RESULT" DROP CONSTRAINT "FK_568c8db36565a640c57a9ca9821"`);
        await queryRunner.query(`ALTER TABLE "CRITERIA" DROP CONSTRAINT "FK_824bf8db29ad093e7eeae585988"`);
        await queryRunner.query(`DROP TABLE "ASSET"`);
        await queryRunner.query(`DROP TABLE "UBP"`);
        await queryRunner.query(`DROP TABLE "USER_UBP_ACCESS"`);
        await queryRunner.query(`DROP TABLE "USERS"`);
        await queryRunner.query(`DROP TABLE "AUDIT_LOG"`);
        await queryRunner.query(`DROP TABLE "TEST_SESSION"`);
        await queryRunner.query(`DROP TABLE "TEST_TYPE"`);
        await queryRunner.query(`DROP TABLE "DM_TEST_TYPE"`);
        await queryRunner.query(`DROP TABLE "DAMAGE_MECHANISM"`);
        await queryRunner.query(`DROP TABLE "EQUIPMENT_TEST_TYPE"`);
        await queryRunner.query(`DROP TABLE "PARAMETER"`);
        await queryRunner.query(`DROP TABLE "TEST_RESULT"`);
        await queryRunner.query(`DROP TABLE "CRITERIA"`);
    }

}
